### ISSUE TITLE
Analyze refactor Magento 2

### ISSUE THREAD

**Issue by albertodoofinder** [doofinder/doofinder-magento#138]
Investigate and analyze improvements and refactor in Magento 2 module.

**Comment by albertodoofinder** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Unplugged-62c7342b32b594001e03d82a/issues/doofinder/doofinder-magento/138?planning-poker) with Zenhub @Aitor-Corrales @eduardogomez97 @ivan-doofinder @sofia-doofinder @pedromcp90

**Comment by Aitor-Corrales** [comment]
This document aims to summarize every opportunity to improve the quality of the code and the processes associated with Doofinder’s plugin for Magento, having as main pillars of this improvement the performance optimization, the readability and the cleanness of the code.

In order to achieve this, we’ll go first from a general sight of the plugin to a more specific one for each of its components.

**General**

- There needs to be changed every endpoint aiming at Helpapp instead of Doomanager.

- Summarize every constant referring to Doomanager at one point so as to be able to change its values whenever needed (mostly for development purposes)(optative).

- Delete the section in the backend that saves the endpoints to doomanager. This section should not be editable in any case by the client.

- Clean up the code to delete every unused variable, import, etc. (P.E: Helper/StoreConfig-getDoofinderAttributes).

- Unify code format using a PSR standard.

- Break up iterations that are no longer useful once their goal is achieved. (P.E: Helper/StoreConfig-setGlobalDisplayLayerEnabled)

- Clean the integration information if the installation of the plugin has not been successful.


**User Experience**

_Create integration_

The fact that the user has to click over a button in order to create an integration is not user-friendly design. The user needs to input no information for this step, making it unnecessary. In order to improve this process, the integration should be created along with other step without any additional interaction from the user.


**Update on save**

_Cron/processor.php_
- There are 4 private functions and the execute/1. The last private function should be deleted because it is not being used.

- Check how are the different products being collected from the database because it seems that there are multiple unnecessary calls to the database. Taking into account that we are talking about an update on save, probably it won’t be many rows (we could always lean on the pagination), so we should try to retrieve and manage the information in just one call and, if possible, one iteration.

- Check the cron-based strategy for update on save. While it’s true it saves calls to doofapi, it makes the update on save to be update on schedule.

_General_
- When you change a price with the update on save enabled, if the product changed is a simple one, whose parent is configurable, the configurable won’t change its price, while it should. It stays with the wrong value until a complete reindex is launched (should it be a maintenance-task?)

- Is there anyone with update on save enabled whose scheduling-time is greater than every 5 minutes? Should we get rid of every other option?

- It would be interesting to remove the possibility of getting enabled or disabled the “update on schedule” and, instead of that, put as the default option something like “once a day”, so as to avoid any confusion to the client.

- Check classes in path Config/Generator/Map/Product because here is the logic of how the update on save manages the pricing behavior. The pricing logic should be unified for both strategies, update on save and API-based indexation. Here are missing virtual products, which should be the same as simple (Convenient further researching).

_Generator/Map/Product.php_
- The current solution provided for the indexing of products in the update on save strategy based on a map of attributes, should be investigated deeply, as it is very different from the one from API-based indexing.

- The function getProductImageLink/1 seems to construct the image link with the “catalog/product” format, which is not optimal (Investigate if this may be cataloged as a bug).


**Model classes**

_ChangedProductRepository.php_
- Public function getAll/0 and getSingle/1 are unused. Does the interface make any sense for this situation?

_Config/Backend/ApiKeyValidation_
- In the beforeSave plugin, it is being validated that the apikey is working, and in order to achieve that, it makes an unnecessary call to listsearchengine.

_Config/Backend/CustomAttributes.php_
- I don’t understand what this class is for.

_Config/Generator/Map/Product/Bundle.php_
- On the update on save strategy, whenever we try to get the price from a bundle product, if this product has special price, the plugin gets the final price. This needs to be investigated, so as to avoid any trouble concerning pricing indexation.

_Indexer/Data/Map/Update/Fetcher/Category.php_
- In the process/2 function, there is an unset working over the iterable object being iterated, and this is a very dangerous and discouraged pattern.

_Indexer/Data/Map/Update/Fetcher/Magento.php_
- In the prepareAttributeValues/3 function, it makes an unnecessary assignation in case both initial conditions are satisfied. Improve this process.


**Helper classes**

_Product_
- In the getProductCategoriesWithParents/2, there are some processes that iterate over the same iterable more than once unnecessarily, making suboptimal the category obtainment. Improve this process.

_Indices_
- Check function and foreach and make it optimal.

_Item_
- The function validateItem/2 is used only to launch a notFound exception in case an Index is not found. Needs further researching to check if this is necessary or not.

_SearchEngine_
- Make the function getSearchEngineByStore/1 to get as parameter directly the store instead of the code in order to avoid having to retrieve the corresponding store again, when in the calling function is already obtained.


**Controller classes**

_AddToCart_
- Check the execute function because there is no return in every flow inside the function.


**Frontend classes**

_initial.js_
Change the entire structure to be able to manage correctly the flows between processes and clean up the code

**Comment by albertodoofinder** [comment]
Please @sofia-doofinder @peillis have a look to this

**Comment by peillis** [comment]
I have no opinion here, do whatever you think is worth.
